# Spring全局配置
spring:
  application:
    name: 论坛系统
  output:
    ansi:
      enabled: always # 控制台输出颜色
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JSON序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # ⽇期格式
    default-property-inclusion: NON_NULL # 不为null时序列化

# 服务器配置
server:
  port: 58080

# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha

# 日志配置
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss # 日期格式
  level:
    root: info # 默认日志级别
    com.bite.forum: debug
  file:
    path: D:/项目学习Java/论坛系统/forum/forum/log # 日志文件路径

# mybatis 相关配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml # 扫描的mapper文件

# 项⽬⾃定义相关配置
lyz-forum:
  login:
    url: sign-in.html # 未登录状况下强制跳转⻚⾯
  index: # ⾸⻚配置节点
    board-num: 9 # ⾸⻚中显⽰的版块个数


