# Spring全局配置
spring:
  application:
    name: 论坛系统
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# 服务器配置
server:
  port: 58080

# 日志配置
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss # 日期格式
  level:
    root: info # 默认日志级别
    com.bite.forum: debug
  file:
    path: D:/项目学习Java/论坛系统/forum/forum/log # 日志文件路径